name: ts-py
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.12,<3.13
  - pip
  - pip:
    - -e .
  
  # install 
  - httpx
  - loguru
  - plotly
  - pydantic >=2,<3
  - pydantic-settings >=2,<3

  # build
  - go-task
  - conda-build
  - anaconda-client
  - hatch
  - hatchling
  - hatch-vcs

  # lint
  - mypy
  - ruff >=0.13,<1

  # test
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-mock